// root -l <file>; copy-paste commands

TCut trigger = "(channel==1 && eetrig && eetrig_match) || (channel==0 && mmtrig && mmtrig_match) || (channel>=2 && emtrig && emtrig_match)";
TCut mllMin12 = "mll>12";
TCut lepReq2525 = "lep_n>=2 && lep_pT[0]>25 && lep_pT[1]>25";
TCut jetReq = "jet_n>=2 && jet_pT[0]>30 && jet_pT[1]>30";
TCut OS = "lep_pdgId[0]*lep_pdgId[1] < 0";
TCut dPhiJetMET = "DPhi_METJetLeading>0.4 && DPhi_METJetSecond>0.4";
TCut EdgeSRLow = trigger + mllMin12 + OS + lepReq2525 + jetReq + dPhiJetMET + "MET>200";
TCut EdgeSRMed = trigger + mllMin12 + OS + lepReq2525 + jetReq + dPhiJetMET + "MET>250" + "HT>400";
TCut EdgeSRHigh = trigger + mllMin12 + OS + lepReq2525 + jetReq + dPhiJetMET + "MET>200" + "HT>700";
TCut EdgeVRLow = trigger + mllMin12 + OS + lepReq2525 + jetReq + dPhiJetMET + "MET>100 && MET<200";
TCut EdgeVRMed = trigger + mllMin12 + OS + lepReq2525 + jetReq + dPhiJetMET + "MET>100 && MET<200" + "HT>400";
TCut EdgeVRHigh = trigger + mllMin12 + OS + lepReq2525 + jetReq + dPhiJetMET + "MET>100 && MET<200" + "HT>700";
TCut region = EdgeVRHigh;
TString regionName = "VR High";
TCanvas *canvas = new TCanvas("canvas","",696,472);
outputTree->Draw("MET-truthMET>>hee(40,-200,200)",region + "channel==1");
outputTree->Draw("MET-truthMET>>hmm(40,-200,200)",region + "channel==0");
outputTree->Draw("MET-truthMET>>hem(40,-200,200)",region + "channel>=2");
hem->Scale(0.5);
hee->SetLineColor(2);
hmm->SetLineColor(4);
hem->SetLineColor(8);
hee->SetStats(0);
hmm->SetStats(0);
hem->SetStats(0);
hee->SetTitle("MET-truthMET " + regionName);
hmm->SetTitle("MET-truthMET " + regionName);
hem->SetTitle("MET-truthMET " + regionName);
hee->Draw();
hmm->Draw("same");
hem->Draw("same");
g1 = new TF1("m1","gaus");
g2 = new TF1("m2","gaus",98,108);
g3 = new TF1("m3","gaus",110,121);
g1->SetLineColor(2);
g2->SetLineColor(4);
g3->SetLineColor(8);
hee->Fit(g1);
hmm->Fit(g2);
hem->Fit(g3);
TLegend* leg = new TLegend(0.6, 0.7, 0.9, 0.9);
stringstream stream;
stream.str("");
TString label1 = "ee Mean: ";
stream<<fixed<<setprecision(2)<<g1->GetParameter(1);
label1 += stream.str();
label1 += " Sigma: ";
stream.str("");
stream<<fixed<<setprecision(2)<<g1->GetParameter(2);
label1 += stream.str();
stream.str("");
TString label2 = "mm Mean: ";
stream<<fixed<<setprecision(2)<<g2->GetParameter(1);
label2 += stream.str();
label2 += " Sigma: ";
stream.str("");
stream<<fixed<<setprecision(2)<<g2->GetParameter(2);
label2 += stream.str();
stream.str("");
TString label3 = "DF Mean: ";
stream<<fixed<<setprecision(2)<<g3->GetParameter(1);
label3 += stream.str();
label3 += " Sigma: ";
stream.str("");
stream<<fixed<<setprecision(2)<<g3->GetParameter(2);
label3 += stream.str();
leg->AddEntry(g1, label1, "f");
leg->AddEntry(g2, label2, "f");
leg->AddEntry(g3, label3, "f");
leg->Draw();
