bsub -q 1nd -o Logs/out_makeTRUTH_142599.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_142599.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_164433.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_164433.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_142585.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_142585.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_176223.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_176223.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_164434.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_164434.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_157599.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_157599.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_142587.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_142587.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_164430.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_164430.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_142600.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_142600.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_176249.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_176249.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_164897.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_164897.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_176218.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_176218.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_164899.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_164899.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_176240.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_176240.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_142596.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_142596.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_176255.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_176255.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_176221.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_176221.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_157591.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_157591.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_176248.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_176248.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_142602.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_142602.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_157586.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_157586.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_164424.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_164424.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_176220.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_176220.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_176252.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_176252.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_176264.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_176264.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_176243.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_176243.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_157578.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_157578.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_157600.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_157600.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_176217.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_176217.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_176227.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_176227.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_176241.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_176241.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_176242.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_176242.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_176219.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_176219.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_157601.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_157601.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_157598.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_157598.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_164431.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_164431.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_176245.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_176245.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_176258.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_176258.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_176260.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_176260.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_157614.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_157614.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_157624.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_157624.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_176251.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_176251.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_157619.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_157619.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_157622.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_157622.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_157574.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_157574.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_142597.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_142597.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_157590.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_157590.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_176259.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_176259.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_157573.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_157573.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_157607.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_157607.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_176257.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_176257.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_157627.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_157627.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_157592.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_157592.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_157594.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_157594.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_157572.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_157572.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_157602.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_157602.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_176250.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_176250.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_157608.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_157608.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_157611.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_157611.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_176263.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_176263.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_157613.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_157613.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_176235.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_176235.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_157587.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_157587.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_142601.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_142601.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_157621.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_157621.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_157585.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_157585.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_176226.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_176226.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_157618.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_157618.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_157583.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_157583.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_176244.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_176244.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_176234.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_176234.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_157593.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_157593.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_164426.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_164426.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_176231.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_176231.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_157576.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_157576.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_142603.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_142603.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_176262.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_176262.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_176265.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_176265.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_157610.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_157610.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_176254.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_176254.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_176236.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_176236.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_142598.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_142598.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_157612.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_157612.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_164428.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_164428.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_176261.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_176261.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_157620.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_157620.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_157623.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_157623.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_157616.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_157616.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_164904.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_164904.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_176246.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_176246.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_142586.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_142586.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_142595.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_142595.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_176239.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_176239.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_176229.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_176229.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_176238.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_176238.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_176253.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_176253.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_157575.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_157575.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_176237.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_176237.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_176233.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_176233.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_157625.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_157625.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_164898.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_164898.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_176216.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_176216.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_176228.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_176228.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_157615.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_157615.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_157584.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_157584.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_157626.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_157626.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_157580.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_157580.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_157617.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_157617.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_157581.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_157581.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_164425.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_164425.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_157579.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_157579.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_164427.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_164427.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_164906.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_164906.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_176230.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_176230.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_176247.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_176247.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_176232.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_176232.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_176224.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_176224.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_142594.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_142594.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_157577.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_157577.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_164429.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_164429.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_157609.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_157609.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_164432.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_164432.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_176256.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_176256.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_176225.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_176225.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_176222.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_176222.sh 
bsub -q 1nd -o Logs/out_makeTRUTH_164905.txt /afs/cern.ch/user/t/tholmes/ZMET/SusyZMETjetsWorkArea/Scripts/HandleSamples/RunScripts/job_makeTRUTH_164905.sh 
